# git aliases
alias gad='git add'
alias gcl='git clean'
alias gcf='git config'
alias gcm='git commit -m'
alias gco='git checkout'
alias gdf='git diff'
alias glo='git log'
alias gmg='git merge'
alias gpl='git pull'
alias gps='git push'
alias grb='git rebase'
alias grs='git reset'
alias grv='git revert'
alias gst='git status'
